from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 1429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 20, 461, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(80)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(340, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.lcd2 = QtWidgets.QLCDNumber(self.frame)
        self.lcd2.setGeometry(QtCore.QRect(30, 430, 711, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcd2.setFont(font)
        self.lcd2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lcd2.setProperty("value", 0)
        self.lcd2.setObjectName("lcd2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(340, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 890, 801, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(-10, 1010, 801, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(720, 0, 61, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.lcd3 = QtWidgets.QLCDNumber(self.frame)
        self.lcd3.setGeometry(QtCore.QRect(30, 580, 711, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcd3.setFont(font)
        self.lcd3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lcd3.setProperty("value", 0)
        self.lcd3.setObjectName("lcd3")
        self.lcd4 = QtWidgets.QLCDNumber(self.frame)
        self.lcd4.setGeometry(QtCore.QRect(30, 740, 711, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcd4.setFont(font)
        self.lcd4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lcd4.setProperty("value", 0)
        self.lcd4.setObjectName("lcd4")
        self.lcd1 = QtWidgets.QLCDNumber(self.frame)
        self.lcd1.setGeometry(QtCore.QRect(30, 270, 711, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcd1.setFont(font)
        self.lcd1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lcd1.setProperty("value", 0)
        self.lcd1.setObjectName("lcd1")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(340, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(340, 700, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "00:00"))
        self.label_2.setText(_translate("MainWindow", "ROOM 1"))
        self.label_3.setText(_translate("MainWindow", "ROOM 2"))
        self.label_6.setText(_translate("MainWindow", "ROOM 3"))
        self.label_7.setText(_translate("MainWindow", "ROOM 4"))
        self.label_4.setText(_translate("MainWindow", "แจ้งเตือนที่ 12 นาที"))  # เปลี่ยนข้อความให้เหมาะสม
        self.label_5.setText(_translate("MainWindow", "แจ้งเตือนเมื่อเกิน 15 นาที"))  # เปลี่ยนข้อความให้เหมาะสม
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())